version: '3'

services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.1
    ports:
    - 9200:9200
    - 9300:9300
    environment:
    - "discovery.type=single-node"

  kibana:
    image: docker.elastic.co/kibana/kibana:6.4.1
    ports:
    - 5601:5601
    environment:
      SERVER_NAME: kibana.local
      ELASTICSEARCH_URL: http://es:9200

  logstash:
    build: ./logstash/
    ports:
    - 9600:9600
    restart: always
    network_mode: "host"
